nome : Verificar e executar script

em : [empurrar]

empregos :
  verificar-arquivo :
    em execução : ubuntu-latest

    passos :
    - nome : Repositório de checkout
      usos : ações/checkout@v2

    - nome : Configurar Python
      usos : ações/setup-python@v2
      com :
        versão python : ' 3.x '

    - nome : Instalar dependências
      executar : |
        solicitações de instalação do pip
        pip instalar matplotlib
    - nome : Executar script Python
      executar : python custom_collections.py
