# Este workflow irá enviar um pacote Python para o PyPI quando uma nova versão for criada
# Para mais informações, veja: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# Este workflow usa ações que não são certificadas pelo GitHub.
# Elas são fornecidas por terceiros e estão sujeitas a
# termos de serviço, política de privacidade e documentação de suporte separados.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          # NOTE: insira suas próprias etapas de construção de distribuição aqui.
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # IMPORTANTE: esta permissão é obrigatória para publicação confiável
      id-token: write

    # Ambientes dedicados com proteções para publicação são altamente recomendados.
    # Para mais informações, veja: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: pypi
      # OPCIONAL: descomente e atualize para incluir a URL do seu projeto PyPI no status de implantação:
      # url: https://pypi.org/p/YOURPROJECT
      #
      # ALTERNATIVA: se o nome da sua versão do GitHub Release for a versão exata do seu projeto no PyPI
      # ALTERNATIVA: descomente a seguinte linha:
      # url: https://pypi.org/project/YOURPROJECT/${{ github.event.release.name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          
