name: Satellite Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib

      - name: Create satellite.ini if not exists
        run: |
          if [ ! -f /home/runner/satellite.ini ]; then
            echo "Arquivo satellite.ini ausente. Criando arquivo de exemplo."
            echo "[config]" > /home/runner/satellite.ini
            echo "param1=value1" >> /home/runner/satellite.ini
            echo "param2=value2" >> /home/runner/satellite.ini
          fi

      - name: Run your actual job
        run: |
          # Comandos que utilizam o arquivo satellite.ini
